### ISSUE TITLE
Open VSX

### ISSUE THREAD

**Issue by ghostdevv** [Serendipity-Theme/old-serendipity#2]
Hey, I have requested this on Serendipity before (https://github.com/Serendipity-Theme/vs-code/issues/17) but not on the old version, and would be great to have it on there too!

I personally use Serendipity sunset v1 because of the added contrast

**Comment by michael-andreuzza** [comment]
You got it!

Get it here:
- https://open-vsx.org/extension/wicked-labs/old-serendipity

**Comment by ghostdevv** [comment]
Ty!!

**Comment by michael-andreuzza** [comment]
> Ty!!

Welcome!
